config_ordinal: 150
configuredCdi:
  alias:
    remote:
      class: com.mamezou.rms.client.api.adaptor.remote.RentalReservationClientRemoteApi
      scope: application
    local:
      class: com.mamezou.rms.client.api.adaptor.local.RentalReservationClientLocalApi
      scope: application
  register:
    - alias: remote
main.manifest.jar: rms-client-ui-console\.jar$
