name: "module-build-action"
description: "build action for monorep module"
inputs:
  module:
    description: "module name"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Java11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn -B -Pcli deploy --file pom.xml
      working-directory: ${{ inputs.module }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
