config_ordinal: 200
#----------------------------------
# Production definition
#----------------------------------
rms:
  server.port: 80
  server.tls.port: 443
  server.tls.passphrase: ${GCM=CyuGtqdglSOPgW4MaUq5XDMFHI8XDS9lahC0lSBJ7DXKdcOxrMTk81zS765ZuSBbz/2d}
  sec.require.encrypt: true
  sec.aes.passphrase: set-by-environment-variable
  h2.user: sa
  h2.password: ${GCM=sPaKo86vpN6S4oZHrDIzyQzZxB4mTSofeZyzf3CLhtYUBvuFsHfoUHDPNoM=}

#----------------------------------
# Addition of Production properties
#----------------------------------
csv.type.temporary.init.data: init-data

