name: rms-build-manual

on:
  workflow_dispatch:
    branches: [ main ]
    inputs:
      module:
        description: 'module name'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java11
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn -B -Pcli deploy --file pom.xml
      working-directory: ${{ github.event.inputs.module }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
