name: rms-distribute-client

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
    paths: 
      - rms-client-api/**
      - rms-client-api-remote/**
      - rms-client-ui-console/**

jobs:
  distribute_client:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            temp-name: "mac"
          - os: windows-latest
            temp-name: "win"
    steps:
      - run: echo ${{ matrix.temp-name }}
