name: rms-build

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
    paths: 
      # Suppressing push event activation. It won't work without `**`
      #- '**'
      - '!.github/**'
      - '!docs/**'
      - '!**.md'
      - '!**.sh'

jobs:
  rms-application-parent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Publish to GitHub Packages Apache Maven
        run: |
          mvn -Pcli clean deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}

  rms-test:
    needs: [rms-application-parent]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ozytso/rms/actions@main
        with:
          module: rms-test

  rms-platform:
    needs: [rms-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Publish to GitHub Packages Apache Maven
        run: |
          mvn -B -Pcli deploy --file pom.xml
        working-directory: rms-platform
        env:
          GITHUB_TOKEN: ${{ github.token }}

  rms-client-api:
    needs: [rms-platform]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Publish to GitHub Packages Apache Maven
        run: |
          mvn -B -Pcli deploy --file pom.xml
        working-directory: rms-client-api
        env:
          GITHUB_TOKEN: ${{ github.token }}

  rms-client-api-local:
    needs: [rms-client-api, rms-service]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Publish to GitHub Packages Apache Maven
        run: |
          mvn -B -Pcli deploy --file pom.xml
        working-directory: rms-client-api-local
        env:
          GITHUB_TOKEN: ${{ github.token }}

  rms-client-api-remote:
    needs: [rms-client-api-local]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn -B -Pcli deploy --file pom.xml
      working-directory: rms-client-api-remote
      env:
        GITHUB_TOKEN: ${{ github.token }}

  rms-client-ui-console:
    needs: [rms-client-api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn -B -Pcli deploy --file pom.xml
      working-directory: rms-client-ui-console
      env:
        GITHUB_TOKEN: ${{ github.token }}

  rms-service:
    needs: [rms-platform]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn -B -Pcli deploy --file pom.xml
      working-directory: rms-service
      env:
        GITHUB_TOKEN: ${{ github.token }}

  rms-service-server:
    needs: [rms-service]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Publish to GitHub Packages Apache Maven
      run: |
        mvn -B -Pcli deploy --file pom.xml
      working-directory: rms-service-server
      env:
        GITHUB_TOKEN: ${{ github.token }}
