name: rms-distribute-client

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
    paths: 
      - rms-client-api/**
      - rms-client-api-remote/**
      - rms-client-ui-console/**

jobs:
  distribute_client:
    runs-on: windows-latest
    #needs: [build_client]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java16
        uses: actions/setup-java@v1
        with:
          java-version: 16 # jpackage required
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Make app-image
        shell: bash
        run: |
          mvn -B -Pcli,copy-libs clean package -DskipTests=true --file pom.xml
          cp ./target/rms-client-ui-console.jar ./target/libs
          APP_NAME=RmsConsole
          MAIN_JAR=rms-client-ui-console.jar
          BUIDL_TYPE=app-image
          JAVA_OPTION=-Dserver.url=https://rms.ext-act.io
          jpackage --name $APP_NAME --input target/libs --main-jar $MAIN_JAR --type $BUIDL_TYPE --java-options $JAVA_OPTION
        working-directory: rms-client-ui-console
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload binary to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: RmsConsoleForWin
          path: rms-client-ui-console/RmsConsole
          retention-days: 1
      - name: Commit to GitHubPages
        shell: bash
        run: |
          git fetch
          git checkout github-pages
          7z a RmsConsoleWin.zip ./rms-client-ui-console/RmsConsole
          mv ./RmsConsoleWin.zip ./binary
          rm -rf ./rms-client-ui-console
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./binary && git diff --cached --exit-code --quiet || git commit -m "Add the rebuild binary" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: github-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
